// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFqSDJhidUr9sJYMfORSCQ-NNNqP9nRk',
    appId: '1:429568883650:web:58181e63a35799fdb5745b',
    messagingSenderId: '429568883650',
    projectId: 'prathmeshsadake-fluttergram',
    authDomain: 'prathmeshsadake-fluttergram.firebaseapp.com',
    storageBucket: 'prathmeshsadake-fluttergram.appspot.com',
    measurementId: 'G-1R6H3H3HJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mns_nF11I3fb455me8A8QcOYFvkk-ts',
    appId: '1:429568883650:android:33506723108bf84ab5745b',
    messagingSenderId: '429568883650',
    projectId: 'prathmeshsadake-fluttergram',
    storageBucket: 'prathmeshsadake-fluttergram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8RL6GIy16bMInU_s6pMPbn0a8qn-M8jE',
    appId: '1:429568883650:ios:8ad9a42a25fd86d4b5745b',
    messagingSenderId: '429568883650',
    projectId: 'prathmeshsadake-fluttergram',
    storageBucket: 'prathmeshsadake-fluttergram.appspot.com',
    iosClientId: '429568883650-nv61ek53taplo1d8rd1ehbnprao9htb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttergram',
  );
}
